-- MySQL Script generated by MySQL Workbench
-- Fri Nov 16 20:27:29 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `id` INT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `encrypted_password` VARCHAR(80) NOT NULL,
  `salt` VARCHAR(10) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `unique_id` VARCHAR(23) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `E-mail_UNIQUE` (`email` ASC),
  UNIQUE INDEX `unique_id_UNIQUE` (`unique_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Film` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Tytul` VARCHAR(100) NOT NULL,
  `CzasTrwaniaMin` INT NOT NULL,
  `OdLat` INT NOT NULL,
  `WersjaJezykowa` VARCHAR(45) NOT NULL,
  `DataPremiery` DATE NOT NULL,
  `Opis` VARCHAR(600) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gatunek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gatunek` (
  `idGatunek` INT NOT NULL AUTO_INCREMENT,
  `NazwaGatunku` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGatunek`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TypMiejsca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TypMiejsca` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nazwa` VARCHAR(50) NOT NULL,
  `Cena` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rezerwacja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rezerwacja` (
  `Klient_idKlient` INT NOT NULL,
  `Film_id` INT NOT NULL,
  `Sala` INT NOT NULL,
  `NumerMiejsca` INT NOT NULL,
  `Rząd` INT NOT NULL,
  `Czas` DATETIME NOT NULL,
  `TypMiejsca_id` INT NOT NULL,
  PRIMARY KEY (`Klient_idKlient`, `Film_id`, `TypMiejsca_id`),
  INDEX `fk_Klient_has_Film_Film1_idx` (`Film_id` ASC),
  INDEX `fk_Klient_has_Film_Klient_idx` (`Klient_idKlient` ASC),
  INDEX `fk_Rezerwacja_TypMiejsca1_idx` (`TypMiejsca_id` ASC),
  CONSTRAINT `fk_Klient_has_Film_Klient`
    FOREIGN KEY (`Klient_idKlient`)
    REFERENCES `mydb`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Klient_has_Film_Film1`
    FOREIGN KEY (`Film_id`)
    REFERENCES `mydb`.`Film` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rezerwacja_TypMiejsca1`
    FOREIGN KEY (`TypMiejsca_id`)
    REFERENCES `mydb`.`TypMiejsca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gatunek_has_Film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gatunek_has_Film` (
  `Gatunek_idGatunek` INT NOT NULL,
  `Film_id` INT NOT NULL,
  PRIMARY KEY (`Gatunek_idGatunek`, `Film_id`),
  INDEX `fk_Gatunek_has_Film_Film1_idx` (`Film_id` ASC),
  INDEX `fk_Gatunek_has_Film_Gatunek1_idx` (`Gatunek_idGatunek` ASC),
  CONSTRAINT `fk_Gatunek_has_Film_Gatunek1`
    FOREIGN KEY (`Gatunek_idGatunek`)
    REFERENCES `mydb`.`Gatunek` (`idGatunek`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gatunek_has_Film_Film1`
    FOREIGN KEY (`Film_id`)
    REFERENCES `mydb`.`Film` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
